filebeat.inputs:
  - type: log
    paths:
      - /logs/books/*.log
      - /logs/authors/*.log

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"

logging.json: true
logging.metrics.enabled: false